/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.Objects.EmptyPanel;
import Control.MainControl;
import Model.Questionnaire.QuestionnaireModel;
import View.Objects.ObjQuest;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author rodri
 */
public class MainView extends javax.swing.JFrame {

    private final MainControl control = MainControl.getInstance();
    private static final MainView viewSingleton = new MainView();
    private final int columns = 5;

    /**
     * Creates new form NewJFrame
     */
    private MainView() {
        initComponents();
        showQuestionnaires();
    }

    public static MainView getInstance() {
        return viewSingleton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jQuestionnaires = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TUXE");
        setMinimumSize(new java.awt.Dimension(610, 380));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 177, 192));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TUXE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seus Questionários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jQuestionnaires.setMinimumSize(new java.awt.Dimension(426, 126));
        jQuestionnaires.setLayout(new java.awt.GridLayout(2, 5, 1, 1));
        jScrollPane1.setViewportView(jQuestionnaires);

        jButtonCreate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonCreate.setText("+ Criar");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jLabel2.setText("Bem-vindo(a)!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButtonCreate)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        // TODO add your handling code here:
        // control é um objeto da classse MainControl que controla essa view
        //o metodo chamado vai dar inicio ao processo de criar um questionnaires
        setEnabled(false);
        control.startCreation();
    }//GEN-LAST:event_jButtonCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewSingleton.defineCloseOperation();
                viewSingleton.setVisible(true);

            }
        ;
    }
    );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jQuestionnaires;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //-------------------------------------------------------------------------//
    
    private void defineCloseOperation() {
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                Initializer.Main.closePogram();
            }
        });
    }
    
    private void completeJPanel(JPanel panel, int x) {
        for (int i = 0; i < x; i++) {
            panel.add(new javax.swing.JPanel());
        }
    }

    private void setLayout(JPanel panel, int countObjects) {
        int lines = getLines(countObjects, columns);
        panel.setLayout(new GridLayout(lines, columns, 1, 1));

    }

    private int getLines(int total, int columns) {
        int lines = (int) Math.ceil((double) total / (double) columns);
        if (total > 5) {
            return lines;
        } else {
            return lines + 1;
        }
    }

    private void showEmptyMessage(JPanel jQuestionnaires) {
        EmptyPanel a = new EmptyPanel();
        jQuestionnaires.setLayout(new GridLayout(1, 1));
        jQuestionnaires.add(a);
    }

    private void addQuestionnaireInJPanel(JPanel panel, QuestionnaireModel questionnaire) {
        if (questionnaire != null) {
            ObjQuest a = new ObjQuest(questionnaire);
            panel.add(a);
        }
    }

    private void addAllQuestionnairesInJPanel(JPanel panel, ArrayList<QuestionnaireModel> questionnaires) {
        for (QuestionnaireModel q : questionnaires) {
            addQuestionnaireInJPanel(panel, q);
        }
        int lines = getLines(questionnaires.size(), columns);
        if (questionnaires.size() < lines * columns) {
            completeJPanel(panel, (lines * columns) - questionnaires.size());
        }
    }

    private void showQuestionnaires() {
        ArrayList<QuestionnaireModel> questionnaires = control.getQuestionnaires();
        if (questionnaires.size() > 0) {
            setLayout(jQuestionnaires, questionnaires.size());
            addAllQuestionnairesInJPanel(jQuestionnaires, questionnaires);
        } else {
            showEmptyMessage(jQuestionnaires);
        }
        jQuestionnaires.revalidate();
        jQuestionnaires.repaint();
    }
    //-------------------------------------------------------------------------//

    public void updateQuestionnaires() {
        jQuestionnaires.removeAll();
        showQuestionnaires();
    }

    public void close() {
        dispose();
    }
    //--------------------------------------------------------------------------//

}
