/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ResponseControl;
import Model.Questionnaire.AnswerItemModel;
import Model.Questionnaire.QuestionnaireModel;
import Model.Questionnaire.TaskModel;
import View.Objects.ObjDomainScale;
import View.Objects.ObjMotivationScale;
import View.Objects.ObjSatisfactionScale;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 * @author rodri
 */
public class ResponseView extends javax.swing.JFrame {

    private static final ResponseControl control = ResponseControl.getInstance();
    private static final ResponseView viewSingleton = new ResponseView();

    private ResponseView() {
        initComponents();
        //initializeObjects(questionnaire);
    }

    public static ResponseView getInstance() {
        return viewSingleton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAdvance = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jTotalNumber = new javax.swing.JLabel();
        jTaskName = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jTask = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jSoftwareName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScalesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TUXE");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 177, 192));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TUXE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 261, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 265, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonAdvance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAdvance.setText("Avançar");
        jButtonAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdvanceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 100, -1));

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 100, -1));

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancel.setText("Cancelar");
        jButtonCancel.setToolTipText("");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 100, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setText("Tarefa:");

        jTotalNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTotalNumber.setText("jT");

        jTaskName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTaskName.setText("jLabel2");

        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setText("de");

        jTask.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTask.setText("n");

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setText("Software:");

        jSoftwareName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSoftwareName.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSoftwareName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTaskName)
                .addGap(152, 152, 152)
                .addComponent(jTask, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTotalNumber)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTotalNumber)
                        .addComponent(jTask))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSoftwareName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jTaskName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 570, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jScalesPanelLayout = new javax.swing.GroupLayout(jScalesPanel);
        jScalesPanel.setLayout(jScalesPanelLayout);
        jScalesPanelLayout.setHorizontalGroup(
            jScalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jScalesPanelLayout.setVerticalGroup(
            jScalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jScalesPanel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 570, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdvanceActionPerformed
        // TODO add your handling code here:
        control.advance(Integer.parseInt(jTask.getText()));
    }//GEN-LAST:event_jButtonAdvanceActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        control.back(Integer.parseInt(jTask.getText()));
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        control.cancel();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     * @param quest the questionnaire that will be shown
     * @return return new view to control keep it
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                viewSingleton.defineCloseOperation();
                viewSingleton.setVisible(true);
                viewSingleton.initializeObjects(control.getQuestionnaire());
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdvance;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jScalesPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jSoftwareName;
    private javax.swing.JLabel jTask;
    private javax.swing.JLabel jTaskName;
    private javax.swing.JLabel jTotalNumber;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables

    private void initializeObjects(QuestionnaireModel questionnaire) {
        jSoftwareName.setText(questionnaire.getApplication());
        jTotalNumber.setText("" + questionnaire.getTasks().size());
        setTask(questionnaire.getTasks().get(0).getName(), 1);
        setScales();
        jButtonBack.enable(false);
    }

    private void setScales() {
        jScalesPanel.setLayout(new java.awt.GridLayout(3, 1, 1, 1));
        jScalesPanel.add(new ObjDomainScale());
        jScalesPanel.add(new ObjMotivationScale());
        jScalesPanel.add(new ObjSatisfactionScale());
        jScalesPanel.revalidate();
        jScalesPanel.repaint();
    }

    private void setScales(int dV, int mV, int sV) {
        //este métod foi criado para restaura a resposta dada a uma tarefa
        //quando o usuário escolhe rever uma resposta, mas falta implementar o 
        //constrturar os outros objetos escalas além do satisfação.
        jScalesPanel.setLayout(new java.awt.GridLayout(3, 1, 1, 1));
        jScalesPanel.add(new ObjDomainScale());
        jScalesPanel.add(new ObjMotivationScale());
        jScalesPanel.add(new ObjSatisfactionScale(sV));
        jScalesPanel.revalidate();
        jScalesPanel.repaint();
    }

    private void setTask(String name, int number) {
        //    System.out.println("name: "+name+" "+number+"/"+total);
        jTaskName.setText(name);
        jTask.setText("" + number);
    }

    private void restore(AnswerItemModel item) {
        System.out.println(item.getDomainValue());
        System.out.println(item.getMotivationValue());
        System.out.println(item.getSatisfactionValue());
        ((ObjDomainScale) jScalesPanel.getComponent(0)).setOption(item.getDomainValue());
        ((ObjMotivationScale) jScalesPanel.getComponent(1)).setOption(item.getMotivationValue());
        ((ObjSatisfactionScale) jScalesPanel.getComponent(2)).setOption(item.getSatisfactionValue());
    }
     private void defineCloseOperation() {
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                Initializer.Main.closePogram();
            }
        });
    }

    public void updateView(String taskName, int taskNumber) {
        if (taskNumber == 1) {
            jButtonBack.enable(false);
        }
        jScalesPanel.removeAll();
        setTask(taskName, taskNumber);
        //if()
        setScales();
    }

    public ArrayList<TaskModel> getTasks() {
        return ResponseControl.getInstance().getQuestionnaire().getTasks();//this.tasks;
    }

    public boolean isAnswered() {
        return ((ObjDomainScale) jScalesPanel.getComponent(0)).isAnswered()
                && ((ObjMotivationScale) jScalesPanel.getComponent(1)).isAnswered()
                && ((ObjSatisfactionScale) jScalesPanel.getComponent(2)).isAnswered();
    }

    public AnswerItemModel getAnswers() {
        String taskName = jTaskName.getText();
        int dV = ((ObjDomainScale) jScalesPanel.getComponent(0)).getAnswer();
        int mV = ((ObjMotivationScale) jScalesPanel.getComponent(1)).getAnswer();
        int sV = ((ObjSatisfactionScale) jScalesPanel.getComponent(2)).getAnswer();
        System.out.println(taskName);
        System.out.println(dV + " " + mV + " " + sV);
        return new AnswerItemModel(taskName, dV, mV, sV);
    }

    public QuestionnaireModel getQuestionnaire() {
        return ResponseControl.getInstance().getQuestionnaire();//this.questionnaire;
    }

    public void close() {
        this.dispose();
    }
}
