/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ResponseControl;
import Model.Questionnaire.AnswerItemModel;
import Model.Questionnaire.QuestionnaireModel;
import Model.Questionnaire.TaskModel;
import View.Objects.ObjDomainScale;
import View.Objects.ObjMotivationScale;
import View.Objects.ObjSatisfactionScale;
import java.util.ArrayList;

/**
 *
 * @author rodri
 */
public class ResponseView extends javax.swing.JFrame {
    private final ResponseControl control = ResponseControl.getInstance();
   /* private final ArrayList<TaskModel> tasks;
    private final String software;
    private final int total;
    private final QuestionnaireModel questionnaire; */  
   
 
    
 
    /**
     * Creates new form ResponseView
     * @param questionnaire
     */
   
    private ResponseView(QuestionnaireModel questionnaire) {
        initComponents();
        initializeObjects(questionnaire);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jTotalNumber = new javax.swing.JLabel();
        jTaskName = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jTask = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelScales = new javax.swing.JPanel();
        jSoftwareName = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jButtonAdvance = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 177, 192));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TUXE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 257, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 262, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label2.setText("Tarefa:");

        jTotalNumber.setText("jT");

        jTaskName.setText("jLabel2");

        label3.setText("de");

        jTask.setText("n");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTaskName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(jTask, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTotalNumber)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTotalNumber)
                        .addComponent(jTaskName)
                        .addComponent(jTask))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelScales.setLayout(new java.awt.GridLayout(3, 1));
        jScrollPane1.setViewportView(jPanelScales);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSoftwareName.setText("jLabel1");

        label1.setText("Software:");

        jButtonAdvance.setText("Avançar");
        jButtonAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdvanceActionPerformed(evt);
            }
        });

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancelar");
        jButtonCancel.setToolTipText("");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSoftwareName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancel)
                                .addGap(317, 317, 317)
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSoftwareName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdvance)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonCancel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdvanceActionPerformed
        // TODO add your handling code here:
        control.advance(Integer.parseInt(jTask.getText()));
    }//GEN-LAST:event_jButtonAdvanceActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        control.back(Integer.parseInt(jTask.getText()));
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        control.cancel();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     * @param quest the questionnaire that will be shown
     * @return return new view to control keep it

     */
    public static ResponseView main(String args[], QuestionnaireModel quest) {
        /* Set the Nimbus look and feel */
       ResponseView view = new ResponseView(quest);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                view.setVisible(true);
            }
        });
        return view;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdvance;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelScales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSoftwareName;
    private javax.swing.JLabel jTask;
    private javax.swing.JLabel jTaskName;
    private javax.swing.JLabel jTotalNumber;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables

      private void initializeObjects(QuestionnaireModel questionnaire) {
        jSoftwareName.setText(questionnaire.getApplication());
        jTotalNumber.setText(""+questionnaire.getTasks().size());
        setTask(questionnaire.getTasks().get(0).getName(), 1);
        setScales();
        jButtonBack.enable(false);
    }
    
    private void setScales() {
        jPanelScales.setLayout(new java.awt.GridLayout(3, 1,1,1));
        jPanelScales.add(new ObjDomainScale());
        jPanelScales.add(new ObjMotivationScale());
        jPanelScales.add(new ObjSatisfactionScale());
        jPanelScales.revalidate();
        jPanelScales.repaint();       
    }
    private void setScales(int dV, int mV, int sV) {
        jPanelScales.setLayout(new java.awt.GridLayout(3, 1,1,1));
        jPanelScales.add(new ObjDomainScale());
        jPanelScales.add(new ObjMotivationScale());
        jPanelScales.add(new ObjSatisfactionScale(sV));
        jPanelScales.revalidate();
        jPanelScales.repaint();       
    }
   
    private void setTask(String name, int number) {
    //    System.out.println("name: "+name+" "+number+"/"+total);
        jTaskName.setText(name);
        jTask.setText(""+number);    
    }
   
    private void restore(AnswerItemModel item){
        System.out.println(item.getDomainValue());
        System.out.println(item.getMotivationValue());
        System.out.println(item.getSatisfactionValue());
        ((ObjDomainScale)jPanelScales.getComponent(0)).setOption(item.getDomainValue());
        ((ObjMotivationScale)jPanelScales.getComponent(1)).setOption(item.getMotivationValue());
        ((ObjSatisfactionScale)jPanelScales.getComponent(2)).setOption(item.getSatisfactionValue());
    }
    
    public void updateView(String taskName, int taskNumber) {
        if(taskNumber==1)
            jButtonBack.enable(false);
        jPanelScales.removeAll();
        setTask(taskName, taskNumber);
        setScales();
    }
   public ArrayList<TaskModel> getTasks(){
       return ResponseControl.getInstance().getQuestionnaire().getTasks();//this.tasks;
   }

    public boolean isAnswered() {
        return ((ObjDomainScale) jPanelScales.getComponent(0)).isAnswered() && 
                ((ObjMotivationScale)jPanelScales.getComponent(1)).isAnswered() &&
                ((ObjSatisfactionScale)jPanelScales.getComponent(2)).isAnswered();
    }
    
    public AnswerItemModel getAnswers(){
        String taskName = jTaskName.getText();
        int dV=((ObjDomainScale) jPanelScales.getComponent(0)).getAnswer();
        int mV=((ObjMotivationScale)jPanelScales.getComponent(1)).getAnswer();
        int sV=((ObjSatisfactionScale)jPanelScales.getComponent(2)).getAnswer();
        System.out.println(taskName);
        System.out.println(dV+" "+mV+" "+sV);
        return new AnswerItemModel(taskName, dV, mV, sV);
    }
    
    public QuestionnaireModel getQuestionnaire() {
        return ResponseControl.getInstance().getQuestionnaire();//this.questionnaire;
    }

    public void close() {
        this.dispose();
    }

  

  
  
}
