/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Objects;

import javax.swing.ButtonModel;
import javax.swing.JRadioButton;

/**
 *
 * @author rodri
 */
public class ObjMotivationScale extends javax.swing.JPanel {

    /**
     * Creates new form ObjScale
     */
    public ObjMotivationScale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMotivation = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Motivation.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, -1, -1));

        buttonGroupMotivation.add(jRadioButton2);
        jRadioButton2.setMnemonic('2');
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton1);
        jRadioButton1.setMnemonic('1');
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton4);
        jRadioButton4.setMnemonic('4');
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton8);
        jRadioButton8.setMnemonic('8');
        add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton7);
        jRadioButton7.setMnemonic('7');
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton6);
        jRadioButton6.setMnemonic('6');
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton5);
        jRadioButton5.setMnemonic('5');
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton9);
        jRadioButton9.setMnemonic('9');
        add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 124, -1, -1));

        buttonGroupMotivation.add(jRadioButton3);
        jRadioButton3.setMnemonic('3');
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 124, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMotivation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables

    public boolean isAnswered() {
        return buttonGroupMotivation.getSelection()!= null;
    }

    public int getAnswer() {
        return buttonGroupMotivation.getSelection().getMnemonic()-48;
    }

     public void setOption(int scaleValue) {
        switch(scaleValue){
            case 1 :
                jRadioButton1.setSelected(true);
            case 2 :
                jRadioButton2.setSelected(true);
            case 3 :
                jRadioButton3.setSelected(true);
            case 4 :
                jRadioButton4.setSelected(true);
             case 5 :
                jRadioButton5.setSelected(true);
            case 6 :
                jRadioButton6.setSelected(true);
            case 7 :    
                jRadioButton7.setSelected(true);
            case 8 :
                jRadioButton8.setSelected(true);
            case 9 :
               jRadioButton9.setSelected(true);
        }
    }
}
